language: node_js

node_js: 0.12

env:
  global:
    - secure: MsCIrHUQKBHVvB9iqJXuv7Ednory1pu8nqOPifRM6q7YI2v+So5V4vspEmL0+LfkrKMYOD5SsirJ69UTtoGchXvOx/IsUWSJ5jibiyF0m5BzS+a46lhzi59OuXAHUtY4/RIYhhrACKOX8Az2qLGgjZ+ff6Yut2hiCcns+t9jRVbfX5Yl/BIpTIH5pIvq0ueIohxk49w7lQXQPdfztLp7e0jTm3zEQ9lJvW2x8jFgsXPmWbKshcqa3eUSIPOXDhFk4UDPirJYGg9N5MPeJZqA8J2/upe3JtrzDJ1vZLdnPP9H9oMW32ICJcvj4ZdLFZ9tyUNyHUcrR1eMBiTihdtvQFs7ZuqAR7mliNKr/Y39WY65DFH690ijI4aOdF9eSYOgY0Qb96yse0A6eD3cPOMx1m+rNaYwJwEfYsEa1YV8WO4rz3ky9PX8afE++OrJjopnmDVPP2SFIUd1y23joJKXtXHKZMCUnQ/BKdaTSz71LNKvtHhCATRrJ6dMTsO4ZnmTSZTjFTsIkfLuXOWOr9F2bD3OQGbtglYTb2QZ332zHk6sTaxsz6JiRGbMT/fCpJveQY1HcZJuPoi1yCWWXq+hyCrPRZgEXM8ApHaB61iTN5GTMrAJjT1PvKZvTKeiGyF+R/4tNrkIecIoFvu8o+ZcCRlT8fgrOxgxclUkNxFXdD0=
    - secure: Hsm/L/VCuWQKFAYLVhVlo/eRMuP5pMim5JfChH59JDSfax7Yo3UL+u3IzXH/2bh1UTN+YYoW+jHf2AtBBpQD2vywFrNc9fhkWRVfbtuiPy9d9zmu9+tcL2UR6JPBUmHIKDfoip8Xv4c1zXa/zyntfl4B1/MbPyJvRcZXUSEOf0ImwE002jQVr1L6GM3t8hnt+vlx0ejm0UDI8X0NmfMaClfx+hipumItAFlze8r9TSrMhJOubzjuy5aYkynvArECHA9iqF+HEqrjPnbzPj4ufz5YgfrHwQKdi2zyjHfRk28g3CnlelYEaxUQQ8erCxnsA5mI3Z1E0ibG+jzSdvT5XxZr7qvomR0lHvP3ksCmWhs566ucGb70YGbUsIfy8k5kP+OerYi81zVPuFBs50e2ibXqhEiBoJnODifVhhjLaF9NiLxfy9sAxgp49ACZ5K2jKSTGevxkZU4DGN5YOUnaCNdQGDhetD7LdAxSN+mq5raz75rkOaLQGvtJYLf8ry3AJ3xn4EwkhgfIARqPGiC11ZH3Q0VrDkJi4nfqW7UlwQRKPcZrtLcFJqwxxRGkZ8UEOqkd4dGA8tIdwqfJ4ubSpJY9a4SYLzPGnr56wXKDbe7Y6S/Sx7UHof+fyMn0tDr1TsiGRPqjIKBphmJ+dYRTTU7lTtX5sTYEdv37WZIUdyg=

install:
  - npm install

script:
  - npm test

after_success:
  - npm run coveralls

notifications:
  email:
    on_failure: change
    on_success: change
